// Generated by scripts/gen-themes.ts from opencode's TUI theme assets
// (packages/tui/src/theme/assets). Dark variants only. Do not edit by hand;
// regenerate instead: bun scripts/gen-themes.ts <assets-dir>
import { defaultConfig, type Theme } from "./config";

export type ThemePreset = { name: string; theme: Theme };

export const THEME_PRESETS: ThemePreset[] = [
  // the tfm default palette (tokyo night flavored) stays first so a fresh
  // install matches a preset exactly and the cycle row does not say "custom"
  { name: "Tokyo Night", theme: defaultConfig.theme },
  { name: "OpenCode", theme: {"bg":"#0a0a0a","sidebarBg":"#141414","sidebarFg":"#eeeeee","sidebarFgMuted":"#808080","accent":"#fab283","accentBg":"#1e1e1e","hoverBg":"#212121","border":"#3c3c3c","divider":"#3c3c3c","white":"#eeeeee"} },
  { name: "Aura", theme: {"bg":"#0f0f0f","sidebarBg":"#15141b","sidebarFg":"#edecee","sidebarFgMuted":"#6d6d6d","accent":"#a277ff","accentBg":"#15141b","hoverBg":"#252525","border":"#2d2d2d","divider":"#2d2d2d","white":"#edecee"} },
  { name: "Ayu", theme: {"bg":"#0b0e14","sidebarBg":"#0f131a","sidebarFg":"#bfbdb6","sidebarFgMuted":"#565b66","accent":"#59c2ff","accentBg":"#0d1017","hoverBg":"#1d2024","border":"#11151c","divider":"#11151c","white":"#bfbdb6"} },
  { name: "Carbon Fox", theme: {"bg":"#161616","sidebarBg":"#1a1a1a","sidebarFg":"#f2f4f8","sidebarFgMuted":"#7d848f","accent":"#33b1ff","accentBg":"#1e1e1e","hoverBg":"#2c2c2d","border":"#262626","divider":"#262626","white":"#f2f4f8"} },
  { name: "Catppuccin", theme: {"bg":"#1e1e2e","sidebarBg":"#181825","sidebarFg":"#cdd6f4","sidebarFgMuted":"#9399b2","accent":"#89b4fa","accentBg":"#11111b","hoverBg":"#303042","border":"#585b70","divider":"#585b70","white":"#cdd6f4"} },
  { name: "Cobalt 2", theme: {"bg":"#193549","sidebarBg":"#122738","sidebarFg":"#ffffff","sidebarFgMuted":"#adb7c9","accent":"#0088ff","accentBg":"#1f4662","hoverBg":"#30495b","border":"#0e1e2e","divider":"#0e1e2e","white":"#ffffff"} },
  { name: "Cursor", theme: {"bg":"#181818","sidebarBg":"#141414","sidebarFg":"#e4e4e4","sidebarFgMuted":"#636363","accent":"#88c0d0","accentBg":"#262626","hoverBg":"#2c2c2c","border":"#0f0f0f","divider":"#0f0f0f","white":"#e4e4e4"} },
  { name: "Dracula", theme: {"bg":"#282a36","sidebarBg":"#21222c","sidebarFg":"#f8f8f2","sidebarFgMuted":"#6272a4","accent":"#bd93f9","accentBg":"#44475a","hoverBg":"#3d3f49","border":"#191a21","divider":"#191a21","white":"#f8f8f2"} },
  { name: "Everforest", theme: {"bg":"#2d353b","sidebarBg":"#333c43","sidebarFg":"#d3c6aa","sidebarFgMuted":"#7a8478","accent":"#a7c080","accentBg":"#343f44","hoverBg":"#3e4446","border":"#7a8478","divider":"#7a8478","white":"#d3c6aa"} },
  { name: "Flexoki", theme: {"bg":"#100f0f","sidebarBg":"#1c1b1a","sidebarFg":"#cecdc3","sidebarFgMuted":"#6f6e69","accent":"#da702c","accentBg":"#282726","hoverBg":"#232221","border":"#403e3c","divider":"#403e3c","white":"#cecdc3"} },
  { name: "Frappe", theme: {"bg":"#303446","sidebarBg":"#292c3c","sidebarFg":"#c6d0f5","sidebarFgMuted":"#949cb8","accent":"#8da4e2","accentBg":"#232634","hoverBg":"#3f4458","border":"#626880","divider":"#626880","white":"#c6d0f5"} },
  { name: "GitHub", theme: {"bg":"#0d1117","sidebarBg":"#010409","sidebarFg":"#c9d1d9","sidebarFgMuted":"#8b949e","accent":"#58a6ff","accentBg":"#161b22","hoverBg":"#20242a","border":"#21262d","divider":"#21262d","white":"#c9d1d9"} },
  { name: "Gruvbox", theme: {"bg":"#282828","sidebarBg":"#3c3836","sidebarFg":"#ebdbb2","sidebarFgMuted":"#928374","accent":"#83a598","accentBg":"#504945","hoverBg":"#3c3a36","border":"#504945","divider":"#504945","white":"#ebdbb2"} },
  { name: "Kanagawa", theme: {"bg":"#1f1f28","sidebarBg":"#2a2a37","sidebarFg":"#dcd7ba","sidebarFgMuted":"#727169","accent":"#7e9cd8","accentBg":"#363646","hoverBg":"#323137","border":"#363646","divider":"#363646","white":"#dcd7ba"} },
  { name: "Macchiato", theme: {"bg":"#24273a","sidebarBg":"#1e2030","sidebarFg":"#cad3f5","sidebarFgMuted":"#939ab7","accent":"#8aadf4","accentBg":"#181926","hoverBg":"#35384d","border":"#5b6078","divider":"#5b6078","white":"#cad3f5"} },
  { name: "Material", theme: {"bg":"#263238","sidebarBg":"#1e272c","sidebarFg":"#eeffff","sidebarFgMuted":"#546e7a","accent":"#82aaff","accentBg":"#37474f","hoverBg":"#3a474c","border":"#1e272c","divider":"#1e272c","white":"#eeffff"} },
  { name: "Matrix", theme: {"bg":"#0a0e0a","sidebarBg":"#0e130d","sidebarFg":"#62ff94","sidebarFgMuted":"#8ca391","accent":"#2eff6a","accentBg":"#141c12","hoverBg":"#132618","border":"#141c12","divider":"#141c12","white":"#62ff94"} },
  { name: "Mercury", theme: {"bg":"#171721","sidebarBg":"#10101a","sidebarFg":"#dddde5","sidebarFgMuted":"#9d9da8","accent":"#8da4f5","accentBg":"#272735","hoverBg":"#2b2b35","border":"#23242e","divider":"#23242e","white":"#dddde5"} },
  { name: "Monokai", theme: {"bg":"#272822","sidebarBg":"#1e1f1c","sidebarFg":"#f8f8f2","sidebarFgMuted":"#75715e","accent":"#66d9ef","accentBg":"#3e3d32","hoverBg":"#3c3d37","border":"#1e1f1c","divider":"#1e1f1c","white":"#f8f8f2"} },
  { name: "Night Owl", theme: {"bg":"#011627","sidebarBg":"#0b253a","sidebarFg":"#d6deeb","sidebarFgMuted":"#5f7e97","accent":"#82aaff","accentBg":"#0b253a","hoverBg":"#162a3b","border":"#5f7e97","divider":"#5f7e97","white":"#d6deeb"} },
  { name: "Nord", theme: {"bg":"#2e3440","sidebarBg":"#3b4252","sidebarFg":"#eceff4","sidebarFgMuted":"#8b95a7","accent":"#88c0d0","accentBg":"#434c5e","hoverBg":"#414752","border":"#434c5e","divider":"#434c5e","white":"#eceff4"} },
  { name: "One Dark", theme: {"bg":"#282c34","sidebarBg":"#21252b","sidebarFg":"#abb2bf","sidebarFgMuted":"#5c6370","accent":"#61afef","accentBg":"#353b45","hoverBg":"#353942","border":"#2c313a","divider":"#2c313a","white":"#abb2bf"} },
  { name: "Orng", theme: {"bg":"#0a0a0a","sidebarBg":"#141414","sidebarFg":"#eeeeee","sidebarFgMuted":"#808080","accent":"#ec5b2b","accentBg":"#1e1e1e","hoverBg":"#212121","border":"#3c3c3c","divider":"#3c3c3c","white":"#eeeeee"} },
  { name: "Osaka Jade", theme: {"bg":"#111c18","sidebarBg":"#1a2520","sidebarFg":"#c1c497","sidebarFgMuted":"#53685b","accent":"#2dd5b7","accentBg":"#23372b","hoverBg":"#232d25","border":"#23372b","divider":"#23372b","white":"#c1c497"} },
  { name: "Palenight", theme: {"bg":"#292d3e","sidebarBg":"#1e2132","sidebarFg":"#a6accd","sidebarFgMuted":"#676e95","accent":"#82aaff","accentBg":"#32364a","hoverBg":"#363a4c","border":"#1e2132","divider":"#1e2132","white":"#a6accd"} },
  { name: "Rose Pine", theme: {"bg":"#191724","sidebarBg":"#1f1d2e","sidebarFg":"#e0def4","sidebarFgMuted":"#6e6a86","accent":"#9ccfd8","accentBg":"#26233a","hoverBg":"#2d2b39","border":"#21202e","divider":"#21202e","white":"#e0def4"} },
  { name: "Solarized", theme: {"bg":"#002b36","sidebarBg":"#073642","sidebarFg":"#839496","sidebarFgMuted":"#586e75","accent":"#268bd2","accentBg":"#073642","hoverBg":"#0d3640","border":"#073642","divider":"#073642","white":"#839496"} },
  { name: "Synth '84", theme: {"bg":"#262335","sidebarBg":"#1e1a29","sidebarFg":"#ffffff","sidebarFgMuted":"#848bbd","accent":"#36f9f6","accentBg":"#2a2139","hoverBg":"#3c3949","border":"#241b2f","divider":"#241b2f","white":"#ffffff"} },
  { name: "Vercel", theme: {"bg":"#000000","sidebarBg":"#1a1a1a","sidebarFg":"#ededed","sidebarFgMuted":"#878787","accent":"#0070f3","accentBg":"#292929","hoverBg":"#181818","border":"#1a1a1a","divider":"#1a1a1a","white":"#ededed"} },
  { name: "Vesper", theme: {"bg":"#101010","sidebarBg":"#101010","sidebarFg":"#ffffff","sidebarFgMuted":"#a0a0a0","accent":"#ffc799","accentBg":"#101010","hoverBg":"#282828","border":"#1c1c1c","divider":"#1c1c1c","white":"#ffffff"} },
  { name: "Zenburn", theme: {"bg":"#3f3f3f","sidebarBg":"#4f4f4f","sidebarFg":"#dcdccc","sidebarFgMuted":"#9f9f9f","accent":"#8cd0d3","accentBg":"#5f5f5f","hoverBg":"#4f4f4d","border":"#4f4f4f","divider":"#4f4f4f","white":"#dcdccc"} },
];
